/// <reference types="expo/types" />

// Pulls in Expo's react-native-web style augmentations (backgroundPosition,
// backgroundSize, percentage width/height, etc.) that the web renderer relies on.
//
// Expo normally emits an `expo-env.d.ts` at the repo root with this same
// reference, but that file is generated by the Expo CLI and gitignored, so a
// clean clone has no reference to `expo/types` and `npm run typecheck` fails
// with TS2345 on every web-only style property. Committing the reference here
// keeps typecheck reproducible from a fresh `git clone && npm ci`.
//
// Harmless if the generated root file also exists — TypeScript de-duplicates
// identical reference directives.
